name: ci
on: push
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.23
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: Copy Repo Files dd
      uses: actions/checkout@v2
    - name: Build
      run: |
       cd app
       go build -o nginx-ui 
    
    - name: Test
      run: go test ./... -v
    